---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/_index.md
  label: Home
- type: directory
  path: content/projects
  label: Projects
  create: documents
  match: "*"
  exclude: "*index.md"
  templates:
  - project
- type: directory
  path: content/services
  label: Services
  create: documents
  match: "*"
  exclude: "*index.md"
  templates:
  - service
- type: directory
  path: content/blog
  label: Blog
  create: documents
  match: "*"
  exclude: "*index.md"
  templates:
  - blog-post
upload_dir: assets/uploads
public_path: uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=develop
  - HUGO_VERSION=0.79.0
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.79.0
