---
label: Blog Post
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: title
- type: list
  name: categories
  label: categories
- type: file
  name: image
  label: image
