---
label: Blog
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: statement
  label: statement
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
