---
label: Home Page
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: field_group
  name: hero
  label: hero
  fields:
  - type: text
    name: heading
    label: Heading
  - name: src
    type: file
    config:
      maxSize: 64
    label: Image
  - type: field_group_list
    name: cta
    label: cta
    fields:
    - type: text
      name: href
      label: href
    - type: text
      name: text
      label: text
- type: field_group
  name: intro
  label: intro
  fields:
  - type: text
    name: overline
    label: overline
  - type: text
    name: heading
    label: heading
  - type: textarea
    name: src
    label: src
  - type: textarea
    name: content
    label: content
- type: field_group
  name: whatwedo
  label: whatwedo
  fields:
  - type: text
    name: headline
    label: headline
- type: field_group
  name: whowework
  label: whowework
  fields:
  - type: text
    name: headline
    label: headline
  - type: field_group_list
    name: clients
    label: clients
    fields:
    - type: text
      name: title
      label: title
    - type: text
      name: img
      label: img
  - type: field_group
    name: quote
    label: quote
    fields:
    - type: text
      name: message
      label: message
    - type: text
      name: author
      label: author
    - type: textarea
      name: image
      label: image
- type: field_group
  name: expertise
  label: expertise
  fields:
  - type: text
    name: overline
    label: overline
  - type: text
    name: headline
    label: headline
  - type: textarea
    name: description
    label: description
