---
label: Home Page
hide_body: true
fields:
- type: text
  name: title
  label: SEO Title
  description: Title that will show in a search
- type: text
  name: description
  label: SEO Description
  description: The description that will show in a search
- type: field_group
  name: hero
  label: Page Hero
  fields:
  - type: text
    name: heading
    label: Heading
  - name: src
    type: file
    config:
      maxSize: 64
    label: Image
  - type: field_group_list
    name: cta
    label: cta
    fields:
    - type: text
      name: href
      label: href
    - type: text
      name: text
      label: text
  description: Main focus of the page
- type: field_group
  name: intro
  label: Business Summary
  fields:
  - type: text
    name: overline
    label: overline
  - type: text
    name: heading
    label: heading
  - type: textarea
    name: src
    label: src
  - type: textarea
    name: content
    label: content
  description: Primary outline of the business
- type: field_group
  name: whatwedo
  label: What We Do
  fields:
  - type: text
    name: headline
    label: headline
- type: field_group
  name: whowework
  label: whowework
  fields:
  - type: text
    name: headline
    label: headline
  - type: field_group_list
    name: clients
    label: clients
    fields:
    - type: text
      name: title
      label: title
    - type: text
      name: img
      label: img
  - type: field_group
    name: quote
    label: quote
    fields:
    - type: text
      name: message
      label: message
    - type: text
      name: author
      label: author
    - type: textarea
      name: image
      label: image
  hidden: true
- type: field_group
  name: expertise
  label: Expertise
  fields:
  - type: text
    name: overline
    label: Overline
    description: Keyword summary or statement
  - type: text
    name: headline
    label: Heading
  - type: textarea
    name: description
    label: Summary
  description: Summary of your expertise
pages:
- content/_index.md
