---
label: InputTypes
hide_body: false
fields:
- name: text_field
  type: text
  config:
    required: true
    min: 10
    max: 50
  label: Text Field
  description: description
  default: This is default text
- name: text_area
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Text Area
- name: number
  type: number
  label: Number
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: toggle
  type: boolean
  label: Toggle
- name: select_field
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Select Field
- name: datefield
  type: datetime
  label: DateField
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- name: colour_picker
  type: color
  label: Colour Picker
  config:
    required: false
    color_format: Hex
- name: tags
  type: tag_list
  default: []
  label: Tags
- name: sortable_list
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: Sortable List
- name: image_upload
  type: file
  config:
    maxSize: 64
  label: Image Upload
- name: gallery_upload
  type: image_gallery
  config: {}
  label: Gallery Upload
- name: field_group
  type: field_group
  config: {}
  fields:
  - name: text_area
    type: text
    config:
      required: false
    label: Text Area
  label: Field Group
- name: repeatable_field_group
  type: field_group_list
  fields:
  - name: text_area
    type: text
    config:
      required: false
    label: Text Area
  config:
    min: 
    max: 
    labelField: 
  label: Repeatable Field Group
- name: block
  type: blocks
  label: Block
  template_types: []
  config:
    min: 
    max: 
- name: include
  type: include
  config: {}
  template: home-page
  label: Include
