---
label: Locations
hide_body: true
fields:
- name: Location1
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Location
  description: Address and contact details
- name: Location3
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Location
  description: Address and contact details
- name: Location2
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Location
  description: Address and contact details
