---
label: Project
hide_body: true
display_field: title
fields:
- type: text
  name: title
  label: Project Title
  description: Title that will show in a search and in thumbnails throughout the site
  config:
    required: true
- type: text
  name: description
  label: Project Summary
  description: The description that will show in a search and in thumbnails throughout
    the site
  config:
    required: true
- type: boolean
  name: featured
  label: Is this a Featured Project?
  description: Select his option to display this project on the home page and featured
    areas around the site
- type: file
  name: image
  label: Hero Image
  description: This is the primary image you want to use on the page and in thumbails
- type: tag_list
  name: tags
  label: What services does this project relate to?
  description: Select which services areas you want this project to appear in
  default: []
- type: list
  name: deliverables
  label: What services where delivered?
  description: Summarise what key items was delivered in this project. Be short and
    succinct
- type: field_group
  name: project
  label: Company Summary
  fields:
  - type: text
    name: name
    label: Company Name
    description: The name of the company or organisation
  - name: src
    type: file
    config:
      maxSize: 64
    label: Company Logo
    description: Upload a logo for this company, preferably a landscape or wide version
  - type: text
    name: location
    label: Project location
- type: list
  name: keystats
  label: Key Achievements
  description: Summarise the key achievements that you provided for this client?
- type: field_group
  name: zones
  label: Project Photos
  fields:
  - type: text
    name: title
    label: title
    hidden: true
    description: This has been removed.
  - type: image_gallery
    name: photos
    label: Add Images
  description: Upload some good quality photos of the project
- type: field_group_list
  name: services
  label: Describe the services provided
  fields:
  - type: text
    name: title
    label: Heading
  - type: textarea
    name: description
    label: Summary
    config:
      wysiwyg: true
      schema:
        format: markdown
  description: Use this section to expand in a little more detail about the specific
    services that were delivered for this project
- type: field_group
  name: quote
  label: Add Testimonial
  fields:
  - type: text
    name: message
    label: Add Quote
  - type: text
    name: author
    label: Persons Name, Position or Company
pages:
- content/projects/bespoke-office-space-for-growing-sunshine-coast-business.md
