---
label: Project
hide_body: true
display_field: title
fields:
- type: text
  name: title
  label: SEO Title
  description: Title that will show in a search
  config:
    required: true
- type: text
  name: description
  label: SEO Description
  description: The description that will show in a search
  config:
    required: true
- type: boolean
  name: featured
  label: Is this a Featured Project?
  description: Select his option to display this project on the home page and featured
    areas around the site
- type: file
  name: image
  label: Hero Image
  description: This is the primary image you want to use on the page and in thumbails
- type: tag_list
  name: tags
  label: What services does this project relate to?
  description: Select when services areas you want this project to appear in
- type: list
  name: deliverables
  label: What services where delivered?
  description: Summarise what key items was delivered in this project. Be short and
    succinct
- type: field_group
  name: project
  label: Project Summary
  fields:
  - type: text
    name: name
    label: Company Name
    description: The name of the company or organisation
  - type: text
    name: location
    label: Project location
- type: list
  name: keystats
  label: Key Achievements
  description: Summarise the key achievements that you provided for this client?
- type: field_group
  name: zones
  label: Project Details
  fields:
  - type: text
    name: title
    label: title
  - type: image_gallery
    name: photos
    label: photos
  description: Provide more detailed information about his project
- type: field_group_list
  name: services
  label: services
  fields:
  - type: text
    name: title
    label: title
  - type: list
    name: description
    label: description
- type: field_group
  name: quote
  label: quote
  fields:
  - type: text
    name: message
    label: message
  - type: text
    name: author
    label: author
