---
label: Team Members
hide_body: false
display_field: title
fields:
- name: title
  type: text
  config:
    required: false
  label: Full Name
- name: position
  type: text
  config:
    required: false
  label: Position
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Summary
- name: src
  type: file
  config:
    maxSize: 64
  label: Photo
- name: linkedin
  type: text
  config:
    required: false
  label: linkedin
- name: weight
  type: number
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
  label: Order
  description: What order should this person appear in. Lower numbers will be prioritised
    (excluding 0 which is ignored).
pages:
- content/team/eve-briere.md
- content/team/matteo-follari.md
- content/team/meg-wilson.md
- content/team/moon-junghyun.md
- content/team/richard-mcpherson.md
