---
label: Team Members
hide_body: true
fields:
- name: title_here
  type: text
  config:
    required: false
  label: Title here
  description: Team title here
- name: team_overview
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Team Overview
  description: Paragraph on the collective team
- name: src
  type: file
  config:
    maxSize: 64
  label: Photo
pages:
- content/team/luke-murray.md
