---
label: Team Members
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Full Name
- name: position
  type: text
  config:
    required: false
  label: Position
- name: src
  type: file
  config:
    maxSize: 64
  label: Photo
pages:
- content/team/luke-murray.md
