---
label: Team Members
hide_body: true
fields:
- name: name
  type: text
  config:
    required: false
  label: Full Name
- name: position
  type: text
  config:
    required: false
  label: Position
- name: summary
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Summary
  description: Summary of team member
- name: src
  type: file
  config:
    maxSize: 64
  label: Photo
pages:
- content/team/luke-murray.md
